name: ctg
channels:
  - defaults
  - conda-forge 
dependencies:
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pip
  - python=3.10
  - scikit-learn
  - sktime
  - pip:
    - optuna
    - pydot
    - tensorflow[and-cuda]
    - wfdb
